
trigger:
- none

pool:
  vmImage: windows-latest

stages:
- stage: ARMDeployment
  jobs:
  - job: Deploy
    steps:
    - task: AzurePowerShell@5
      inputs:
        azureSubscription: 'Nipun Bahri Subscription(bf0f6779-86d2-467e-8226-10f92a8ad378)'
        ScriptType: 'FilePath'
        ScriptPath: 'deploy.ps1'
        azurePowerShellVersion: 'LatestVersion'
